//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcokul.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogretmen
    {
        public int ogretmenid { get; set; }
        public string ogretmenadı { get; set; }
        public string ogretmensoyadı { get; set; }
        public Nullable<int> bolumid { get; set; }
        public string emekli { get; set; }
    
        public virtual bolum bolum { get; set; }
    }
}
