//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcokul.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        public int ogrenciid { get; set; }
        public string ogrenciadi { get; set; }
        public string ogrencisoyadi { get; set; }
        public string mezuniyet { get; set; }
        public Nullable<double> kredi { get; set; }
        public Nullable<int> bolumid { get; set; }
    
        public virtual bolum bolum { get; set; }
    }
}
